name: Run unit tests and SAST scan on the source code

on: push

jobs:
  sonarcloud:

    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0' # Change this to your .NET version

      # Setup Java (required for SonarCloud Scanner)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Required version for SonarCloud Scanner

      # Install SonarCloud Scanner
      - name: Install SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v2

      # Run SonarCloud Analysis
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Add your SonarCloud token to GitHub Secrets
        run: |
          dotnet-sonarscanner begin /k:"katesagay_devsecops-dotnet-github-actions-end-to-end-assignment" /o:"katesagay" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  synk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@3.0.3
      - name: Restore dependencies
        run: dotnet restore SomeConsoleApplication.sln
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: synk
    name: Run DAST scan on the web application
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         ref: main
     - name: ZAP Scan
       uses: zaproxy/action-baseline@v0.6.1
       with:
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        target: 'http://testphp.vulnweb.com/'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'

